### ISSUE TITLE
Unable to Pause and Resume Source Record

### ISSUE THREAD

**Issue by DizzyBHigh** [exeldro/obs-source-record#104]
Been trying to Pause and Resume the recording Via StreamerBot and directly in OBS

OBS says Stream has paused and the main recording from OBS pauses and restarts as expected.

The Source Record continues recording in the background, regardless of the pause state until the recording is stopped.

**Comment by jaminmc** [comment]
I think a better title would be "Source record does not pause when pausing OBS recording."

Looking as the sourcecode, it seems the plugin only monitors recording starting and stopping and doesn't have the logic to pause and resume... So this would have to be programmed as a feature.

**Comment by exeldro** [comment]
Added to version 0.4.0
