### ISSUE TITLE
Frame rate specification addition

### ISSUE THREAD

**Issue by Tallicia** [exeldro/obs-source-record#117]
Would it be possible to add to the source record filter, in the encoder section, the framerate to record at?

https://trac.ffmpeg.org/wiki/ChangingFrameRate

**Comment by exeldro** [comment]
there is a frame rate divisor option now in version 0.3.5

**Comment by Tallicia** [comment]
This is fantastic, Thank you so much! This significantly helps optimize and reduce wasted resources! 

Would it be possible to get 3/4, 2/3 and 7/8 divisors so it drops frames but not quite as much as 50% or more
for 3 of 4 drop every 4th frame, 
for 2/3 drop every 3rd frame etc

Or would be it be easier to specify a target frame rate and calculate the closest divisor? This would be ideal when the main frame rate changes, to avoid having to go change all the source-record divisors.

**Comment by Tallicia** [comment]
Let me know if I should close this issue and open another or if the above comments are relatively trivial.

**Comment by exeldro** [comment]
`obs_encoder_set_frame_rate_divisor` is used and that only supports whole numbers
https://github.com/obsproject/obs-studio/blob/e8968ba7152120129eddb8f78850819a01530a1b/libobs/obs.h#L2198

**Comment by Tallicia** [comment]
Thank you as always!

Thanks for pointing at the core OBS culprit. I'll close this and open something with OBS to better provide means of frame rate adjustment..

**Comment by Tallicia** [comment]
I added a request in OBS here: https://ideas.obsproject.com/posts/2722/allow-target-fps-reduction-fractional-framerate-divisor-ex-supp-90fps-80fps-75-fps-to-60-or-45-or-30
