### ISSUE TITLE
When I use the plugin and switch scenes, the same game source used in other scenes will be black and cannot be captured

### ISSUE THREAD

**Issue by PuDood** [exeldro/obs-source-record#123]

**Comment by exeldro** [comment]
I was not able to replicate the issue.
Can you provide more information? What version of OBS and the plugin?
What are the steps to reproduce the issue?

**Comment by PuDood** [comment]
I'm so sorry, I later found out that this might be a problem with the new version of OBS

OBS：30.2.3

Computer system: Windows 11 Home Chinese Edition
Version: 24H2

Game: Genshin Impact
