### ISSUE TITLE
i can start the record with hotkey, but cant end it so no recordings in the folder.

### ISSUE THREAD

**Issue by Sabrex97** [exeldro/obs-source-record#124]
I started installing the plugin and doing everything stated in yt tutorials. trying to get different recordings of my webcam and gameplay. but i cant seem to get any recordings from the plugin, tried everything i'd say. reinstalling it, changing encoders, tried having all 3 different encoders. all the same. 
without hotkeys, with hotkeys.

With the hotkeys i can get it to start and it shows 2 files in my folder, but im not able to stop anything and get any actual file sizes or working videos from it. Default OBS recordings still does work.

**Comment by exeldro** [comment]
What do you do to try to end the recording? What does happen? What file format and muxer is used?

**Comment by exeldro** [comment]
What version of source record and OBS are you using?
I was not able to replicate the issue with OBS 31 beta3 and Source Record version 0.4.0

**Comment by Sabrex97** [comment]
> What version of source record and OBS are you using? I was not able to replicate the issue with OBS 31 beta3 and Source Record version 0.4.0

OBS version 30.2.3 and i thought  Source Record 0.3.5 i thought. i see there is a new 0.4.0 now. im going to check it right away if its solved for me now maybe.

**Comment by Sabrex97** [comment]
> What version of source record and OBS are you using? I was not able to replicate the issue with OBS 31 beta3 and Source Record version 0.4.0

so i installed the 0.4.0 version and i can actually do it now finally.
I have a final question, is there any way to get the plugin working to record the scene's without having to trigger hotkeys?

**Comment by exeldro** [comment]
you can enable and disable the filter to start and stop recording

**Comment by Sabrex97** [comment]
> you can enable and disable the filter to start and stop recording

got ya! ty!
