### ISSUE TITLE
Source Record Enable only hotkey only works the first time

### ISSUE THREAD

**Issue by tonywingmah** [exeldro/obs-source-record#126]
V0.4
OB31 beta 1 and Beta 3
To reproduce on PC
Recording mode - always
disable Source record filter filter
Hotkey turn on source record filter  - recording will start
Hotkey turn off source record filter  - recording will stop
Hotkey turn on source record filter  - **recording will not start**

Recording mode - Virtual Camera 
disable Source record filter filter
Push - Virtual camera control button - recording will start
Hotkey turn off source record filter  - recording will stop
Hotkey turn on source record filter  - **recording will not start**

In both cases the filter is turning on and off but the new file is not generated

**Comment by exeldro** [comment]
Should be in version 0.4.1

**Comment by tonywingmah** [comment]
Works now with windows OBS - Thanks
