### ISSUE TITLE
Label Chapter Markers

### ISSUE THREAD

**Issue by tonywingmah** [exeldro/obs-source-record#128]
Chapter Markers works well. We want to use it for sports. Can we add chapter names like 
Goal, miss, turnover, pass and etc and have it hotkey programmable so that the recording have the appropriate label with the push of a key? This would work well for training.

**Comment by exeldro** [comment]
You can use an OBS websocket vendor request `record_add_chapter` with `chapter_name` set
If you don't have an OBS websocket client, the Move Action filter from the Move plugin can do it like this:
![afbeelding](https://github.com/user-attachments/assets/911a2266-3dc9-466a-a66f-a45fabf819ae)
```
{
    "vendorName": "source-record",
    "requestType": "record_add_chapter",
    "requestData": {
        "source": "Media Source",
        "filter": "Source Record",
        "chapter_name": "test"
    }
}
```
the move action filter can be triggered by hotkey or stream deck button

**Comment by tonywingmah** [comment]
I setup the move filter as shown in your example, but when I toggle the move action the recording file is split! So if I toggle 5 times the file will split 5 times. Can you investigate?

**Comment by tonywingmah** [comment]
@exeldro Works now on PC. If the Mac version is ready I can test it too
