### ISSUE TITLE
Audio Quality Setting Cannot be changed (nor does it follow obs stream or recording default setting)

### ISSUE THREAD

**Issue by musicalnerd** [exeldro/obs-source-record#129]
In earlier version of source record and with OBS 27, source record would default to using the streaming or recording settings for audio. Now, it seems to default to something else.

![image](https://github.com/user-attachments/assets/8eb14cd5-f01a-4420-98c2-4042e3b57a60)

These settings would allow for a FLAC file (16 bit, 44.1hKz) to be recorded in AAC 320k kbps, capturing the entire audio spectrum. it seems to encode in AAC at a much lower kbps.

Is this a known issue?
Cheers,
Frank

**Comment by exeldro** [comment]
Changing audio encoder is a feature that has not been made yet, as there have been no to little requests for it.

**Comment by musicalnerd** [comment]
What is the behavior of the plugin currently since nothing is paramatrizable? Does it default to OBS' recording options?

**Comment by exeldro** [comment]
It uses ffmpeg_aac with default settings.

**Comment by ScriptTiger** [comment]
I would also just like to show my interest here. And I think https://github.com/exeldro/obs-source-record/issues/85 was alluding to this, as well. And perhaps if anyone else is interested, you could just react to this comment, just to keep things clean and get a loose gauge of interest.

**Comment by musicalnerd** [comment]
@exeldro  thanks for the reply. is there a way to change the ffmpeg_aac default settings in ffmpeg directly or it is handled by the your plugin?

**Comment by ScriptTiger** [comment]
@musicalnerd FFmpeg allows you to override every default, but this plug-in is simply handing the audio off without any such overrides. Additional arguments can certainly be added though to make things more flexible. @exeldro is simply waiting to make sure there is enough interest as to not implement unnecessary features. However, if you would like to fork this repo and update the `source-record.c` on your own, you could also do that.

**Comment by musicalnerd** [comment]
@ScriptTiger ok great, i had started putting some FFmpeg commands, but i wasn't sure if it had to be done in the plugin or in the OBS record options via FFmpeg.

**Comment by exeldro** [comment]
I made an audio encoder option on stream today, the test build can be found on the bottom of this page:
https://github.com/exeldro/obs-source-record/actions/runs/11980479987

**Comment by ScriptTiger** [comment]
@musicalnerd Is that what ChatGPT said you needed? FFmpeg has a command-line front end, but FFmpeg, at its core, is a collection of software libraries and OBS uses it through its C API. It needs C bindings, not command-line arguments. The command-line front end doesn't even come included with OBS since it doesn't need it.

@exeldro You are the man! Thank you so much, bro!

**Comment by musicalnerd** [comment]
Yes, i asked chatgpt to modify the command line i use in PowerShell when i
export / extract audio in aac from recorded videos from stream. I explained
to it that i was using source record and if it could tweak it for OBS.
Clearly i wrongly influenced GPT into that line.

Thanks for the guidance i wasn't even aware it wasn't at all what was
necessary !

**Comment by musicalnerd** [comment]
@exeldro  you are an war machine, thank you!!!
