### ISSUE TITLE
[PATCH] some cleanups to code inconsistencies

### ISSUE THREAD

**Issue by rse** [exeldro/obs-source-record#14]
I'm still experiencing OBS Studio crashes when one stops OBS Studio or switches the scene collection once Source Record is part of the game (more details on this in a separate issue soon if I found out more). During debugging the situation I've stumbled over at least two code inconsistencies. These are unrelated to my original crashes, of course. But I would like to already flush a patch to the Source Record sources which fixes those two inconsistencies. One is a useless call to `obs_get_encoder_codec` and the other is that the `streamOutput` is not cleaned up in `source_record_filter_filter_remove` although the `fileOutput` and `replayOutput` are. Find my patch attached.

[cleanup.diff.txt](https://github.com/exeldro/obs-source-record/files/6681389/cleanup.diff.txt)

**Comment by exeldro** [comment]
Fixed with https://github.com/exeldro/obs-source-record/commit/343426e9dc1fd898513e33ed061ab6aad5852768
