### ISSUE TITLE
Inconsistency detected: "showing" count not correctly handled

### ISSUE THREAD

**Issue by rse** [exeldro/obs-source-record#19]
I've detected another inconsistency: the "showing" count for a source is not handled correctly, I think. Source Record uses just a single boolean flag `output_active`, enables it at maximum three times (for recording, streaming and replaying) and with this INCREMENTS the "showing" count up to three times, but DECREMENTS the "showing" count at maximum one time in `source_record_filter_destroy`. I think Source Record should split this single boolean flag into three boolean flags and use to correctly increment between 1 and 3 times the "showing" count and in `source_record_filter_destroy` also correctly decrement the "showing" count between 1 and 3 times.

**Comment by exeldro** [comment]
`output_active` is checked before `obs_source_inc_showing` is called so both the increment and the decrement should only be called once, calling it separate per type of output should not be necessary

**Comment by rse** [comment]
Oh, my mistake: you're right: there is a protecting check around the increments. Good catch! Sorry for raising a not existing bug.
