### ISSUE TITLE
Video and audio are out of sync

### ISSUE THREAD

**Issue by Nama** [exeldro/obs-source-record#33]
Hi,

I'm using this plugin to record my cam and game separately. Audio wasn't recording without manual setup, cause of #32 I guess.
I'm using nvenc, cause of #1.

Audio on both recordings are out of sync. The audio is delayed. The recording needs to be long enough to get out of sync, like an hour. I first thought it must have something to do with #7, but the fps and lengths of my files are correct. The audio seems to be cut off at the end.

(Ignore CQP, that's not the value I'm using)
![grafik](https://user-images.githubusercontent.com/2297270/129812926-39c3afa3-8590-4854-9a51-25efebd965ff.png)
![grafik](https://user-images.githubusercontent.com/2297270/129812946-e3df0da3-a83d-443e-a208-88d264a3ce26.png)

**Comment by Patrey142** [comment]
I have this same issue and i think i know why it happens.
It seems like every time a frame is dropped in-game source record just skips over it but the audio keeps going like normal, so over time it adds up

**Comment by AUbillaOliva** [comment]
Hello, any update to this issue? I'm having the same problem. I noticed in the video, there are a few moments where the velocity of the recording spikes and then goes back to normal, but as @Patrey142 said, the audio keeps going normal.

My config of the plugin: 
![config](https://user-images.githubusercontent.com/29866563/148986771-ee2e17d6-5896-4dea-a658-c210dea424f4.png)
![config](https://user-images.githubusercontent.com/29866563/148986907-7ccabbeb-dbd6-4695-9980-acf6f9e19f0c.png)
![config](https://user-images.githubusercontent.com/29866563/148987018-3d698e71-bba9-4718-9d1a-61c539fb6346.png)

I have not yet tried to change my stream obs settings, I will give more information as soon as I notice changes in the recordings
