### ISSUE TITLE
Don't record if source is not visible

### ISSUE THREAD

**Issue by Nama** [exeldro/obs-source-record#35]
Sources which are hidden (crossed eye) are recorded regardless.

Would be nice, if I wouldn't have to go to filters to deactivate recording.

**Comment by exeldro** [comment]
A source can be added to multiple scenes multiple times, so it being hidden on 1 place does not indicate anything. You can set a hotkey to disable the source record filter. Does that work for you?

**Comment by Nama** [comment]
> so it being hidden on 1 place does not indicate anything.

You are right. So doing different scenes will not help either. I guess I need to make different scene collections so I don't forget about the source record state. But this makes maintaining the scenes harder...

Thank you, I guess there's nothing you can do about this.
