### ISSUE TITLE
Hardware encoder for Mac m1

### ISSUE THREAD

**Issue by nschurmann** [exeldro/obs-source-record#52]
Hi! I'm using a MacBook Pro m1 Max, the idea is really cool however when I'm recording with the 264 hardware encoder it starts to glitch the image. I was thinking that maybe we could use the hevc_videotoolbox encoder for recording the sources, however is not an option available in macOS. Also the tag hvc1 should be added in order for the videos to be played by QuickTime or imported into Final Cut Pro x.

Thanks!

**Comment by exeldro** [comment]
This should now be fixed with version 0.3.1 of the plugin
