### ISSUE TITLE
Feature request: stream instead of record (or at least record via FFmpeg)

### ISSUE THREAD

**Issue by rse** [exeldro/obs-source-record#8]
Feel free to ignore this request if you think it is not appropriate, but I use and like your Source Record and it is the closest solution (from a functionality point of view) to a functionality I'm still seeking for in addition: **Source Stream, i.e., the possibility to stream (via RTMP or SRT) individual sources (or scenes)**!

### Motivation

Let me explain my scenario to better understand this perhaps strange feature request. We ingest presenters through Microsoft Teams meetings as it causes no real burden for the presenters (because VDO.Ninja for some of them is still too much -- just don't ask, please). There we ingest the presenters via NDI into OBS Studio, mix everything together and then finally both record and broadcast the results. This already works fine, except for the point that Teams always dramatically reduces the resolution of the presenters to 480p or even 360p (even when locally pinned). To allow for a better resolution of the presenters and the content, in addition we provide a small OBS Studio distribution to presenters (primarily a ZIP file and scripts to run a "obs64.exe --portable") which pass-through the camera 1:1, but uses Source Record to also locally record both the camera and the captured desktop. These local recording are then uploaded after the event to allow us to at least provide a better resolution in the event recording, even if the event broadcasting still had to be done with the reduced resolutions.

If Source Record could not just locally record, but stream individual scenes and/or sources via RTMP or SRT, then the presenters could live stream both their camera and their captured desktop (in parallel!) to our central event director and let him ingest the higher resolution person and content. The Teams meeting itself would be still required, as it allows more than one presenter to talk to each other, but local NDI feeds could be replaced with the remote RTMP or SRT feeds. As presenters always have both a camera and a content feed, one cannot use the regular streaming functionality of OBS Studio, of course. It just can stream a single scene on program. 

### Summary and Alternative

So, similar to what Source Record is compared to the global Recording functionality, a Source Stream could be compared to the global Streaming functionality: allow per scene or source streaming! Such a functionality would be absolutely awesome and unique, I think. At least I was not able to achieve parallel streams at all.

I've no real knowledge about the OBS Studio internals, but in case it would be too complex to reuse or reimplement the streaming functionality on a per scene/source basis directly from within Source Record, a sufficient alternative would be that Source Record can "record" to a FFmpeg sub-process (via its "image2pipe" input filter) and let FFmpeg do all the streaming work. For this just add two knobs to Source Record: one to enable/disable this FFmpeg based "recording" and one input field to specify the entire FFmpeg CLI options.

**Comment by rse** [comment]
I've poked around in your Source Record source code and in the OBS Studio source code. Please prove me wrong, but I think your Source Record is actually already VERY close to the mentioned functionality. You are already using `obs_output_create("ffmpeg_muxer", ...)` and if I understand the OBS Studio internals correctly, this functionality is used by OBS Studio both for recording and streaming. So, perhaps Source Record does not even require large changes to be able to also stream. Well, perhaps you also have to just slightly adjust the settings dialog and allow RTMP/SRT URLs and some FFmpeg options to be passed to the "ffmpeg_muxer" (or alternatively the "ffmpeg_output"?)

**Comment by rse** [comment]
In addition to the above description, let me add the reason from my perspective why this functionality really fits into Source Record, although one might think, on the first spot, this is a completely different OBS Plugin. Although it *technically* is about *streaming* a scene or source, *logically* it is about *remote recording* a scene or source!

So, I'm not talking about broadcasting particular sources as "programs" of a live event. Instead, the goal is to remote (mix and then) record those sources. So, it is usually never needed for the OBS Studio at the director side of an event, but for the local OBS Studio instances of the decentral participants of an event whose *multiple* sources have to be individually ingested remotely into the studio's recording. So, I'm primarily talking about the use of Source Record to support using OBS Studio for assembling sources and not mixing sources.

**Comment by exeldro** [comment]
My first try is in #10

**Comment by rse** [comment]
I've seen that you've now already merged the changes to "master". I've now once again test-driven the binary from the corresponding Github Actions job. Everything worked just fine -- at least under Windows where I'm doing all my video stuff. So, a version 0.2.0 with those changes certainly could be released now. Excellent work, Exeldro.

**Comment by rse** [comment]
Oh, I see: you now even released everything as version 0.2.0. Perfect. Thank you very much for your support! You're awesome.
