### ISSUE TITLE
Source Record changes itself to Bitrate where CRF was set

### ISSUE THREAD

**Issue by mpek** [exeldro/obs-source-record#86]
I was setting my recordings to CRF 20 and when getting back to change a value, it shows "Bitrate 2500 Kbps" where "CRF 20" stood last time. 
This happens everytime and it's repeatable.

These are my settings, I'm trying SR with: 

Encoder: Software (x264)
Rate Control: CRF
CRF: 20
Keyframe Interval: 0
CPU Usage (higher = less CPU): veryfast
Profile: (None)
Tune: (None)
x264 option: none

Steps to error: 
Then close that window. Close OBS. Open OBS. Open SR window from that source and boom it shows "Bitrate 2500 Kbps" where "CRF 20" stood last time. Rate Control still shows "CRF".
If you close that window now, it records at 2500 Kbps!
That's how i recognized it. The recorded bitrate was much too small. 

Could you please confirm if this is happening on your end as well?

**Comment by mpek** [comment]
Described behavior changed with OBS version 29.1.3. 
Source record, does not show changed settings anymore, it just records to 2 MBit/s regardsless what ever you set within CRF.

Workaround is: Choosing CBR and a bitrate of lets say 10 MBit/s, it does stay at 10 MBit/s when you revisit the settings page and do recordings. I was used to work with CRF/H.264 and CQP/HEVC but at least you can record in a higher bitrate than 2 MBit!

**Comment by exeldro** [comment]
This should be fixed since 0.3.5
